### ISSUE TITLE
Caja doesn't align the icons.

### ISSUE THREAD

**Issue by annada-behera** [mate-desktop/caja#1316]
#### Expected behaviour
The icons should be in a grid. Without the grid, it looks ugly and out of place.

#### Actual behaviour
The icons in the Caja file manager are not aligned in a grid. It seems to be aligned in rows but not in columns. Caja even breaks the name of long file and directory names, and yet it doesn't align them.

I believe that this is not a duplicate of https://github.com/mate-desktop/caja/issues/373 because even though it is similar, that issue is about alignment in Desktop, this is for the Caja file manager.

#### Steps to reproduce the behaviour
Go to any directory with many files and variable length file names.

#### MATE general version
1.22.1

#### Package version
`mate-desktop-1.22.1_1`

#### Linux Distribution
Void Linux

#### Link to downstream report of your Distribution
https://github.com/void-linux/void-packages/tree/master/srcpkgs/caja

####Screenshot
![ss](https://user-images.githubusercontent.com/8300770/68389824-dd1c7b00-0189-11ea-9147-e2de4ed2a04f.png)

**Comment by lukefromdc** [comment]
OK, I just confirmed this: it happens when you you turn on "text beside icons" in caja's preference dialog (or set org>mate>caja>icon-view>labels-beside-icons to TRUE), which is not the defaut and from this I wonder how well it has ever been tested since the gtk3 transition.

If you turn off text beside icons, you will get text rendered underneath the icons and the grid will line up.

**Comment by annada-behera** [comment]
> If you turn off text beside icons, you will get text rendered underneath the icons and the grid will line up.

No. That's not true.
![ss2](https://user-images.githubusercontent.com/8300770/68451109-7cd21b80-0213-11ea-845b-8a33425da85d.png)

By the way, I like "text beside icons". Please fix that too.

**Comment by lukefromdc** [comment]
I do not get that problem with text below icons, for some reason you are getting one very wide icon that does not fit. Not sure why but not something I or anyone else can debug without being able to duplicate it first. As for the "text besides icons" issue, that is probably beyond my own ability to fix but this is a team effort so hopefully someone familiar with that part of the code will get to it.

**Comment by lukefromdc** [comment]
Are you using compact layout (compact layout in icon view not compact view) by any chance? I just confirmed that compact layout will do this, and when I resized a caja window to the size you posted I had to use compact layout to get that many icons showing. 

If so, we have a bug in compact layout unless the author of that code prioritized getting as many icons into a limited space over a grid arrangement.

In the normal icon view and even more so on the desktop, grids that work  better one way than another are a very old sore spot dating far back into the nautilus/GNOME 2 era/

**Comment by annada-behera** [comment]
I am not using the Compact layout in Icon view. The "Use compact layout" is unchecked. Look at the screenshot and tell me what other option I can check/uncheck to get grid layout. Thank you.
![ss3](https://user-images.githubusercontent.com/8300770/68455606-c9245800-0221-11ea-8e72-dce515d74899.png)

**Comment by lukefromdc** [comment]
I don't know of any others offhand. One thing you can try is manually resizing
that one wide icon to get it to fit, option should be in the icon right-click menu.

What zoom level are you using, and what
screen resolution? Normaly that many icons don't fit in a window that
size. Also test turning thumbnails off and back on, I'm wondering if we have a
thumbnailer problem with that one wide icon.

Test another icon theme too,
it is a known issue in at least some GTK3 versioms that if an icon is not
available small enough (e.g too large a minimum.size set for scalable icons
and no others provided) that the offending icon will render oversize.

**Comment by raveit65** [comment]
I can't reproduce it with my Mate installation using 1.23.x developer releases on fedora 30 and caja use icon-view.
The culprit document is presentation.pdf in you screenshots?
I guess this document use a thumbnail and not an icon?
For me the text wrapping of you your files is looking weird. Maybe this is another kind of problem described here https://github.com/mate-desktop/caja/issues/1284
Can you post your pango version please?

**Comment by Zurd** [comment]
Can you do a "ls -lha" in that folder? In both images, the L of the experimental folder is misplaced which is weird, same thing between the O and the N of presentation, seems like there's a wrong character at this place.

**Comment by Zurd** [comment]
I downloaded Void Linux, put on a USB key and booted with it as a LiveCD and I can reproduce the bug. Everything is fine and works as expected, however, when you check "Use compact layout", you can reproduce the bug. You can just create folders/empty documents with the same name (experimental, representation, etc.). And unchecking it doesn't do anything, it's like there's a cache of the folder layout that is still being used. New folders are fine unless you check the compact option again.

Running gsettings list-recursively | grep -i tighter will show that the compact option is configured properly (true or false). The option is called "org.mate.caja.icon-view default-use-tighter-layout".

I cannot reproduce in Linux Mint, Caja 1.22.1 because the compact option doesn't do anything (another bug?).

As a solution, turn off the compact layout option, use View / Reset View to Defaults in each folder where the problem is and never turn on the compact layout.

**Comment by Lapazlane** [comment]
I experience this issue, both with and without compact layout, if I am arranging manually. I'm not sure if this is a bug or is it something I have to live with because of using manually arranged layout? 

![Screenshot at 2021-04-10 21-12-15](https://user-images.githubusercontent.com/82288072/114283422-8e8ba400-9a41-11eb-85b7-99f0f1f281f0.png)

This is a simple example to illustrate the issue, that doesn't look too bad, but I have far more complex layouts than this in other folders.

I have to be able to arrange file icons in specific groups, orders, spacing etc to support specific taxonomies, and I would much rather be able to have these files lines up neatly if possible! Thank you.

**Comment by lukefromdc** [comment]
Forcing manual layouts to a grid would be a problem for other users who might say, need a different grid density. There would have to be a way to turn this on and off, like "keep aligned" on the desktop. Trouble is, as I found a long time ago working on that desktop, the data needed to determine icon positions isn't all stored with the icon (nor is this even all done from code in the same source file) and fixing that is major, major work.

**Comment by Lapazlane** [comment]
Ok, thank you for the speedy clarification.

**Comment by harlekin777** [comment]
This issue seems related to issue #644 (desktop icons overlap). All Nautilus-based file managers inherited this problem, but it was solved 2017 in Nemo, i.e. Cinnamon (!!!). Why do you not simply import some necessary code from Nemo to solve it in Caja as well? I imagine (as a layman), that would be easy. The overlapping/missing alignment (especially if you insert a usb stick) is so annoying that I actually totally avoid using Mate, even though I do like it otherwise. And over the years there have been endless bug reports/complains about this truly bizarre behavior. When I mentioned Nemo's solution in #644 a while ago, there was no reaction at all. I simply cannot understand this absurd situation.

**Comment by harlekin777** [comment]
@lukefromdc Probably it is a lot of work, if you do it from scratch. But probably it would be much easier, if you import the necessary bits from Nemo, which shares a lot of common code with Caja, had the same problem until 2017 and solved it.

**Comment by lukefromdc** [comment]
I don't find any reference in that issue or anything linked to it showing the actual commits
to Nemo for this, and I do find references to having to make this user selectable and worse,
having to forcibly auto-arrange a user's desktop on upgrade to get rid of the old icon 
position data, with the user having to then manually change a default preference to get 
back the ability to rearrange icons.

**Comment by harlekin777** [comment]
Sorry for the late answer. I appreciate your reply. 
Cinnamon fixed the ugly overlapping of icons (especially when you insert a usb stick) by using a grid. It looks nice. See https://github.com/linuxmint/nemo/issues/108. If you worry about losing your icon positions, one can simply make the grid optional.

**Comment by lukefromdc** [comment]
In that discussion the only actual commit I can find is https://github.com/t-oster/nemo/commit/ae0262eef48dc547e96b4742a7dc2169593e3679 which changes some layout parameters. There are also some new files in Nemo referring to a grid, still cannot find the source of them but the commit history makes it look like this may have been many commits
