### ISSUE TITLE
when deleting a file, the cursor resets to the top

### ISSUE THREAD

**Issue by bart9h** [mate-desktop/caja#347]
The cursor should stay in place: move to the next file, or the previous if the deleted file was the last one.
##

**Comment by NiceandGently** [comment]
Same with creating a new file, the creted new file is always out of view.
I see this this jump also in mate-appearence-properties (gtk3) when i switch to another theme, very annoying when i work on themes.

**Comment by ZrN-kAyDqY** [comment]
The cursor stays in place in 1.8.2 and 1.10.3 also, using list view.  I like the way things are because I don't use icon or compact view, though someone could try to make the case for more consistent behavior across list view, icon view, and compact view (select *something* to bart9h's point).  Since the sorting is done ascending on filename for compact and icon view, I wouldn't see a problem with the next one selected being the next one ascending (beneath the one just deleted).

**Comment by flexiondotorg** [comment]
As others have reported, this cursor move to the item below the deleted one.

**Comment by bart9h** [comment]
On in list or compact view it works. In icon view, the cursor reset to the top.

I just tried it on Caja 1.8.2

There are some cases where icon view is preferred, like on a folder with pictures. This bug really annoys when you're deleting some of them for a cleanup.
So I think this should be fixed for icon view too.

**Comment by monsta** [comment]
@flexiondotorg: we need to confirm that it still happens in recent versions, like 1.16 or 1.18. No reason to keep it open if it only affects 1.8.

**Comment by tanertas** [comment]
This "move to top feature" of Caja makes reasonable browsing experience with keyboard almost impossible. I switched from Pcmanfm to Caja and now I have to deal with this thing. I'm using 1.22.1 and I can't believe that this "feature" didn't have altered since first reported five years ago.
