### ISSUE TITLE
Invisible cursor in dark themes, or wrong text/bg color in rename textbox

### ISSUE THREAD

**Issue by aykevl** [mate-desktop/caja#688]
When renaming a file while using any of the dark themes (BlackMATE, Blackbird, High Contrast Inverse), the cursor is practically invisible.
This  occurs in Icons view and Compact view, List view works properly. In the non-working views, the textbox has black text on a white background with a light cursor. In List view, the textbox has the style of the rest of the theme (dark background, white text), making the cursor visible. I prefer the text box as in the List view, as it is more consistent with the rest of the theme. Maybe the issue really is that the textbox has mostly wrong colors, not following the rest of the theme (except for the cursor, apparently).

Screenshot of a rename (note the almost invisible cursor between `u` and `n`):
![screenshot at 2016-12-01 22-17-52](https://cloud.githubusercontent.com/assets/729697/20813055/7387a35c-b814-11e6-90cf-244cb69e7e13.png)

System: Debian stretch (testing), Caja 1.16.1.

**Comment by raveit65** [comment]
Imo, this can be set with carret-color in themes.

**Comment by lukefromdc** [comment]
The right place to set this is in caja-css, so ALL dark themes are fixed. There's only one problem and it is a nasty one: caret-color is only recognized by GTK 3.20 or later so if it's in caja.css in GTK 3.18 or earlier the file throws an error and won't load. Thus we would need to different versions of caja.css and either a buildtime selector or a runtime selector to pick the right version. Doing it at build time requires that configure.ac detect/declare the GTK versionagain and select the right file, not sure how to do that. I could easily set this up for runtime selection with two files, but installing two when only one will be loaded is a bit more bloat.

If we don't want to fool with that sort of thing at all I can easily fix this in BlackMATE but that leaves the other dark themes broken here. Not sure what to do

**Comment by raveit65** [comment]
Using different caja.css sounds very complicated for me and isn't the carret-color not different for light themes?
I prefer to fix it in BlackMate only and 3 party themes can use it as reference.

**Comment by raveit65** [comment]
I forgot to say, for me this is a theme issue as gtk+ provide a setting for it.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-themes/commit/1147914097234d4d6fda9aff0353d7e698fd7667

fixes this for BlackMATE in master

**Comment by lukefromdc** [comment]
The gtk 3.22 and 3.20 branches of BlackMATE are out of sync, I can't fix that right now. That needs to be resolved so this can be applied to them

**Comment by lukefromdc** [comment]
The actual source of this bug is that the dark theme's entry theming is overridden by caja.css, but the caret-color in the theme is not as it isn't in caja.css.  The result is that Caja ignores the normal .entry theme except the caret color.   We only do this because otherwise the entry remains unthemed and nearly unusable on any theme that does not explicitly support caja. Nemo has the same issue on the desktop but only the desktop.  I will play with this a bit, as much as possible should be fixed in Caja to support all themes. 

I think the issue is that we have

```
    gtk_style_context_add_class (gtk_widget_get_style_context (GTK_WIDGET (label)),
                                 GTK_STYLE_CLASS_ENTRY);
```

in eel-editable-label.c and some GTK 3.20/22 themes do not define .entry at all. Thus, what we need is to use the style context from GtkEntry itself, not add the style class. That would properly support the themes-and would not break the fix in BlackMATE that will be available for existing Caja 1.16 as of the next point release because the style class would not be used.

A related bug is that in at least one theme (Raleigh), many colors defined in gtk.css for the renaming labels are not defined. I have no idea if that is true for any other theme, but the result is the renaming labels are unusable in Raleigh, one of the themes shipped with Gtk itself. Fixing this in Caja by using the entry theme and removing it from caja.css would also fix this. Lastly I just found a missing comma in caja.css and will fix that now.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/commit/6ec1d86a500590e5a02bbddf054b88897f2a973c fixes the missing comma in caja.css, now to see if I can help the entry not following themes situation. That will be a branch so others can test it if i get any results

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/690
and
https://github.com/mate-desktop/mate-themes/pull/154

are meant to be used together to fix all of this and allow Caja's renaming labels to be themed without breaking those themes that do not explicitly support Caja. BlackMATE now uses its normal entry theme in eel-editable label including a clearly visible white caret (required reverting https://github.com/mate-desktop/mate-themes/commit/1147914097234d4d6fda9aff0353d7e698fd7667). Adwaita and Raleigh work properly too, as when the theme does not support Caja the fallback is applied.

https://github.com/mate-desktop/caja/pull/690  splits caja.css into two files loaded with two different priorities so themes can override all of it except the color of desktop text and the required transparency of all widgets shown over the desktop background. That loads with priority "APPLICATION" and the rest with priority "THEME". Also creating a branch and PR for mate-themes as BlackMATE and ContrastHighInverse require adjustment. 

Tested in every MATE theme plus Raleigh and Adwaita and my own UbuntuStudio_Legacy theme with GTK 3.22, only BlackMATE and ContrastHighInverse needed adjustments. Also tested with all references to the mate rename labels stripped out but .entry defined in the theme, that worked too. This was to see if such themes would have the invisible caret or other such issues, no such problems came up.

If these are merged they could be cherrypicked for Caja 1.16 so that an incompatable version of BlackMATE never has to be released.

**Comment by lukefromdc** [comment]
BlackMATE branch merged with
https://github.com/mate-desktop/mate-themes/commit/e067ae3885e9b57cbf53a3a1bb282505399e9372
(revert the previous caret visibility fix,as  this would make it invisibe again with the functional theme)

https://github.com/mate-desktop/mate-themes/commit/5bd6942ad7ed10fda2b4b41b8f0694063dc70afa
(ContrastHighInverse: Fix Caja rename labels when theme actually applied )

and
https://github.com/mate-desktop/mate-themes/commit/e74e29105e664c7e204db5d1ba31b08e96b4cdbc
( BlackMATE: make caja renaming labels more readable )

**Comment by monsta** [comment]
Guys, did these BlackMATE changes make it into some 3.22 release? I failed to find anything in 3.22 branch...
I'm asking because https://bugs.debian.org/853288 seems to be not fixed yet. Debian Testing currently has mate-themes 3.22.6 and Caja 1.16.2.

**Comment by raveit65** [comment]
We released 3.22.10 at 10-04-2017 !!!
I am really afraid about supporting debian if those maintainers don't update.

**Comment by monsta** [comment]
Ok, but do you usually release 3.22.x from master or 3.22 branch?

**Comment by raveit65** [comment]
I release always from branches and master and 3.22 should be similar, but i see that some commits between 2016-12-02 and 2016-16.24 are missing in 3.22 branch, sigh.
https://github.com/mate-desktop/mate-themes/commits/gtk3.22?after=ce25d93d0582102927a026cb9ea1c75955b815a2+104
https://github.com/mate-desktop/mate-themes/commits/master?after=6a72c195f8e365ac269d7af7d37ce24234bdf59b+104

**Comment by raveit65** [comment]
I cherry-picked 4 missing commits from master to 3.22 and3.20 branch.
@lukefromdc 
Can you please take a look at it? Hope that  i didn't make  a mistake....

**Comment by lukefromdc** [comment]
A quick check of this in BlackMATE 3.22 seemed to work fine, giving a white cursor on a dark background as written for master. Debian Unstable is frozen right now, it's old stuff to the point that to test GNOME's new packages I had to get them from Ubuntu. To get bugfixes into Debian Stable will surely require 1.16 point releases for MATE packages other than themes, what's going on with the old theme version I have no idea.

**Comment by raveit65** [comment]
I released 3.22.11 and 3.20.20 today with the fixes.
But i guess poor debian user have to wait for debian-10 for the fix    ;-)

**Comment by monsta** [comment]
> some commits between 2016-12-02 and 2016-16.24 are missing in 3.22 branch, sigh.

That's what I was asking about :slightly_smiling_face:

**Comment by monsta** [comment]
Debian Unstable shouldn't be frozen like Testing, but they probably don't upload latest upstream releases now. Fixes for Testing should be uploaded to Unstable first, so I guess they keep it for that purpose now.
Some maintainers might upload latest stuff to Experimental repo instead.
