### ISSUE TITLE
[List View] SHIFT+ENTER When creating new documents results in default names

### ISSUE THREAD

**Issue by epgfm** [mate-desktop/caja#698]
When creating a new document using right click -> create document -> [Empty File or template] the new document is created and focus is immediately on the rename state, which allows one to immediately enter the new name.
However when one holds shift when pressing enter after writing the new name, what was entered is discarded and the default name is used instead.
This happens a lot to me when I create files such as README.TXT, would it be possible to change the code so that SHIFT+ENTER has the same behavior as ENTER ?
Edit: using Ubuntu MATE 16.04.1 with MATE 1.12.1

**Comment by raveit65** [comment]
Hmm,
**if** it is possible i am in worry that other user blame us ' What you did with shift+ enter'.
Why do you press the shift button when you don't want to press this button?

**Comment by epgfm** [comment]
I'm not doing it on purpose, it's just when I write a filename in allcaps, I almost always hit enter before  remembering I have to release the shift key. I'm not sure if Shift+Enter has any other uses when the rename mode is active.

**Comment by kn00tcn** [comment]
i think there should be a whitelist of what escapes or cancels the text input... probably only the escape key?

for accepting text input, enter while ignoring anything else pressed at the same time as enter, & clicking out onto something else should also accept (unless it's to drag the caja window if that's possible, not sure if it depends on the window manager/decorator)

**Comment by monsta** [comment]
@sc0w hmm I can't reproduce it with current master and 1.18 branches... maybe it was fixed as a side effect of https://github.com/mate-desktop/caja/pull/853?

**Comment by sc0w** [comment]
@monsta 

I can't reproduce this issue with caja 1.18.4 (without https://github.com/mate-desktop/caja/pull/853)

**Comment by monsta** [comment]
Ok, I tested some older releases as well. So I can't reproduce it even in 1.12.7 which is in Ubuntu 16.04 repos.

@epgfm can you still reproduce this?

**Comment by sc0w** [comment]
...and I can't reproduce the issue with caja 1.8.2 and 1.16.6

**Comment by epgfm** [comment]
I can still reproduce the issue in 1.18.4-0ubuntu2 (Ubuntu MATE 17.10), though the behaviour evolved somewhat. Now on top of the file falling back to default name, the new file is also opened.
I'm not sure if this package version comes without #853.

**Comment by monsta** [comment]
This is even more weird - the new file shouldn't be auto-opened...

**Comment by sc0w** [comment]
I installed 1.18.4-0ubuntu2 packages in my debian testing system, and I can't reproduce the issue, I think caja isn't related

**Comment by kn00tcn** [comment]
how long are you holding the enter key?

haha, i just opened caja in xfce, pressing shift+enter on a folder opens it in a new tab while still in rename mode (& continues to open new tabs if i dont let go of the buttons)

**Comment by kn00tcn** [comment]
oh wait... i was doing that to existing files

on NEW empty file, i confirm shift/ctrl/alt+enter loses what i wrote AND opens it/opens properties

caja-1.18.4-2.fc26

**Comment by epgfm** [comment]
OK, new information: it only happens in list view.

**Comment by sc0w** [comment]
@epgfm  yes, now I can confirm, the file can't rename with shift+enter and the file opens, in list view

**Comment by monsta** [comment]
That's good info - now I confirm it too.

**Comment by sc0w** [comment]
more info:

rename -> control + enter

in list view opens the file

**Comment by sc0w** [comment]
This behavior is handled in **/src/file-manager/fm-list-view.c** in the function **key_press_callback**, here:

https://github.com/mate-desktop/caja/blob/master/src/file-manager/fm-list-view.c#L1169

seems caja ignores the rename status, and try to open the selected file

**Comment by monsta** [comment]
Fix is now released in version 1.18.5.
