### ISSUE TITLE
Gtk+-3: Caja cannot scroll with touchpad or mouse to bottom of a folder

### ISSUE THREAD

**Issue by pyaazkaparatha** [mate-desktop/caja#755]
In my various folders there are more files so i have to scroll down to see them all but i am unable to do after upgrading to F26. The scroll doesn't go till the end. Changing the zoom size or layout allows to scroll to the bottom. Default zoom is 100%. The only requirement is to have enough files so that scrolling downwards is needed.

**Comment by raveit65** [comment]
Please post more info?
Like caja package version?
Did you installed MATE-1.18 from updates-testing?
Did you restart your Box?
This is needed after update to MATE-1.18.
Are you using iconview/listview/compactview?
Is there a reason why you don't give us this important information before you open a report?

**Comment by pyaazkaparatha** [comment]
Sorry i should have. 

MATE caja 1.18.0
mate-desktop-1.18.0-1.fc26.x86_64 updates-testing repo 
Yes i have restarted several times. Using it for 2 days.
I am using Iconview with 100% zoom. The phenomenon does not occurs in list/compact view. Also in some folders it happens at 150% zoom too but never in full zoom. The scrolling stops and vibrates and doesn't reaches the bottom.

**Comment by pyaazkaparatha** [comment]
![screenshot at 2017-03-31 17-41-00](https://cloud.githubusercontent.com/assets/9029649/24549935/3e493bba-160b-11e7-8a39-395c9bfe5334.png)

**Comment by raveit65** [comment]
Hmm,  why is places sidebar black?
Did you painted it?
I can't reproduce that here in my f26 development box with  1.18.
Honestly i never saw that in the last months using rawhide/f26.
I will check that in a VM with clean packages from fedora repos.
And can you scroll down with dragging the slider of the scrollbar with the mouse?

**Comment by raveit65** [comment]
Btw, are you using a mouse or a touchpad?

**Comment by pyaazkaparatha** [comment]
Touchpad.

**Comment by raveit65** [comment]
Ok, we switched from obsolete synaptics to libinput driver for touchpads.
I will update my notebook if i find some free time.

**Comment by raveit65** [comment]
It isn't worth to open an report at redhat bugzilla for it as it is possible that we have a bug in libinput driver itself.
Do you see that with other applications too?
You can install nemo filebrowser to confirm.

**Comment by pyaazkaparatha** [comment]
I tried it with nemo and it doesn't occurs. I tried with atleast 15 folders. I also did not see any such behaviour with firefox.

**Comment by lukefromdc** [comment]
Someone who has a touchpad will need to test this, mouse scrolling works fine.

**Comment by raveit65** [comment]
I can't reproduce it with f24 Mate-1.18 (gtk3) and from my coprs repo and libinput driver.
https://copr.fedorainfracloud.org/coprs/raveit65/Mate-GTK3/ 
I used /etc/ dir in maximized mode for testing.
So, it is possible that this issue is f26 alpha related, Mate or libinput driver.
For better debuging please uninstall xorg-x11-drv-synaptic if installed, this driver isn't needed any more.
And please answer to **all** my questions.
Output of
```
xinput list
xinput list props <id-of-your-device> 
```
Do you use one-finger-scrolling or two-finger-scrolling ?
Please post your touchpad settings in mate-mouse-properties?

**Comment by raveit65** [comment]
> > And can you scroll down with dragging the slider of the scrollbar with the mouse?

> I did it but it doesn't helps.

Hmm, does scrolling with the mouse work?

**Comment by pyaazkaparatha** [comment]
I tried in /etc dir and it happens there too. The glow appears at bottom signifying that it can't scroll further but there is still more to scroll left.

>bash-4.4$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ HP TrueVision HD                        	id=9	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=10	[slave  keyboard (3)]
    ↳ HP WMI hotkeys                          	id=12	[slave  keyboard (3)]
    ↳ HP Wireless hotkeys                     	id=13	[slave  keyboard (3)]
bash-4.4$ xinput list-props 4
Device 'Virtual core XTEST pointer':
	Device Enabled (140):	1
	Coordinate Transformation Matrix (142):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	XTEST Device (259):	1
bash-4.4$ 
![screenshot at 2017-04-01 15-55-53](https://cloud.githubusercontent.com/assets/9029649/24577918/6d9cb6ba-16c6-11e7-9af1-144f7c6d3415.png)

I use two finger scrolling
The synaptics driver was not installled.

I have a mouse but it doesn't works with laptop as mouse is PS/2

**Comment by pyaazkaparatha** [comment]
I arranged a mouse and yes the problem still occurs with the mouse.

**Comment by raveit65** [comment]
I think this is your touchpad or not ?

> ⎜ ↳ SynPS/2 Synaptics TouchPad id=11 [slave pointer (2)]

Can you check with 'xinput list-props 11' if libinput is used, please?

> The glow appears at bottom signifying that it can't scroll further but there is still more to scroll left.

I quess with glow you mean a overshoot setting from theme.
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/Menta/gtk-3.0/gtk-widgets.css#L256

> I arranged a mouse and yes the problem still occurs with the mouse.

Ok, it look like it isn't input device related.
....why i can't reproduce this with caja-1.18 on my mainbox with f26...
I need to install unpatched caja from fedora repo.

**Comment by pyaazkaparatha** [comment]
>bash-4.4$ xinput list-props 11
Device 'SynPS/2 Synaptics TouchPad':
	Device Enabled (140):	1
	Coordinate Transformation Matrix (142):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Tapping Enabled (277):	1
	libinput Tapping Enabled Default (278):	0
	libinput Tapping Drag Enabled (279):	1
	libinput Tapping Drag Enabled Default (280):	1
	libinput Tapping Drag Lock Enabled (281):	0
	libinput Tapping Drag Lock Enabled Default (282):	0
	libinput Tapping Button Mapping Enabled (283):	1, 0
	libinput Tapping Button Mapping Default (284):	1, 0
	libinput Accel Speed (285):	0.000000
	libinput Accel Speed Default (286):	0.000000
	libinput Natural Scrolling Enabled (287):	0
	libinput Natural Scrolling Enabled Default (288):	0
	libinput Send Events Modes Available (262):	1, 1
	libinput Send Events Mode Enabled (263):	0, 0
	libinput Send Events Mode Enabled Default (264):	0, 0
	libinput Left Handed Enabled (289):	0
	libinput Left Handed Enabled Default (290):	0
	libinput Scroll Methods Available (291):	1, 1, 0
	libinput Scroll Method Enabled (292):	1, 0, 0
	libinput Scroll Method Enabled Default (293):	1, 0, 0
	libinput Disable While Typing Enabled (294):	1
	libinput Disable While Typing Enabled Default (295):	1
	Device Node (265):	"/dev/input/event4"
	Device Product ID (266):	2, 7
	libinput Drag Lock Buttons (296):	<no items>
	libinput Horizontal Scroll Enabled (297):	0
bash-4.4$ 


Yes  i meant the theme overshoot glow.

> I need to install unpatched caja from fedora repo.

Mine is not a clean install. I have many other packages installed.

**Comment by raveit65** [comment]
Same, with caja from fedora repo.
[rave@mother mate-themes]$ rpm -qa caja
caja-1.18.0-1.fc26.x86_64
I don't run in this issue on my main box.

**Comment by raveit65** [comment]
I have just update my notebook to f26 with 1.18.
Luckily i don't have the issue.
Sorry, i don't what i can do more to reproduce this.

**Comment by pyaazkaparatha** [comment]
I have made this Video

![output](https://cloud.githubusercontent.com/assets/9029649/24579773/05a2f90a-16eb-11e7-932d-def687820d66.gif)

also this 

>Apr 01 11:00:44 localhost.localdomain dbus-daemon[1002]: [session uid=1000 pid=1002] Activating via systemd: service name='org.gtk.vfs.UDisks2VolumeMonitor' unit='gvfs-udisks2-volume-monitor.service' requested by ':1.28' (uid=1000 pid=1082 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 11:00:47 localhost.localdomain dbus-daemon[1002]: [session uid=1000 pid=1002] Activating via systemd: service name='org.gtk.vfs.GPhoto2VolumeMonitor' unit='gvfs-gphoto2-volume-monitor.service' requested by ':1.28' (uid=1000 pid=1082 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 11:00:47 localhost.localdomain dbus-daemon[1002]: [session uid=1000 pid=1002] Activating via systemd: service name='org.gtk.vfs.AfcVolumeMonitor' unit='gvfs-afc-volume-monitor.service' requested by ':1.28' (uid=1000 pid=1082 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 15:52:08 localhost.localdomain dbus-daemon[1000]: [session uid=1000 pid=1000] Activating via systemd: service name='org.gtk.vfs.MTPVolumeMonitor' unit='gvfs-mtp-volume-monitor.service' requested by ':1.28' (uid=1000 pid=1081 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 15:52:08 localhost.localdomain dbus-daemon[1000]: [session uid=1000 pid=1000] Activating via systemd: service name='org.gtk.vfs.AfcVolumeMonitor' unit='gvfs-afc-volume-monitor.service' requested by ':1.28' (uid=1000 pid=1081 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 15:52:23 localhost.localdomain dbus-daemon[1000]: [session uid=1000 pid=1000] Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service' requested by ':1.28' (uid=1000 pid=1081 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 18:58:02 localhost.localdomain dbus-daemon[1070]: [session uid=1000 pid=1070] Activating via systemd: service name='org.gtk.vfs.UDisks2VolumeMonitor' unit='gvfs-udisks2-volume-monitor.service' requested by ':1.27' (uid=1000 pid=1150 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 18:58:04 localhost.localdomain dbus-daemon[1070]: [session uid=1000 pid=1070] Activating via systemd: service name='org.gtk.vfs.MTPVolumeMonitor' unit='gvfs-mtp-volume-monitor.service' requested by ':1.27' (uid=1000 pid=1150 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 18:58:05 localhost.localdomain dbus-daemon[1070]: [session uid=1000 pid=1070] Activating via systemd: service name='org.gtk.vfs.GPhoto2VolumeMonitor' unit='gvfs-gphoto2-volume-monitor.service' requested by ':1.27' (uid=1000 pid=1150 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 18:58:05 localhost.localdomain dbus-daemon[1070]: [session uid=1000 pid=1070] Activating via systemd: service name='org.gtk.vfs.AfcVolumeMonitor' unit='gvfs-afc-volume-monitor.service' requested by ':1.27' (uid=1000 pid=1150 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 01 18:58:11 localhost.localdomain dbus-daemon[1070]: [session uid=1000 pid=1070] Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service' requested by ':1.27' (uid=1000 pid=1150 comm="caja " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")

**Comment by raveit65** [comment]
I understood you're problem already.
Log looks like a selinux problem. Try disable it.

**Comment by pyaazkaparatha** [comment]
The log is unrelated to this problem right?

**Comment by lukefromdc** [comment]
I've never seen this happen in my netbook with its touchpad on Debian Unstable with any version of Caja built with any version of GTK3

**Comment by raveit65** [comment]
For getting shure that we don't have a problem with overshoot animation please create such a file and reload the theme by switching to another one and back.
~.config/gtk-3.0/gtk.css
```
/* result is disable overshoot */
overshoot.top {
    background-color: transparent;
    background-image: none;
    background-size: 10px 0px;
    background-repeat: repeat-x;
    background-origin: content-box;
}

overshoot.bottom {
    background-color: transparent;
    background-image: none;
    background-size: 10px 0px;
    background-repeat: repeat-x;
    background-origin: content-box;
}

overshoot.left {
    background-color: transparent;
    background-image: none;
    background-size: 0px 10px;
    background-repeat: repeat-y;
    background-origin: content-box;
}

overshoot.right {
    background-color: transparent;
    background-image: none;
    background-size: 0px 10px;
    background-repeat: repeat-y;
    background-origin: content-box;
}
```
Such a file overrides theme settings per user.

**Comment by pyaazkaparatha** [comment]
I created the file as you said. The overshoot goes away but the scrolling problem remains. I tried different themes the problems exists but not with arc theme i have installed in local theme installation. It is old but it is the one which does not shows this behaviour.

**Comment by raveit65** [comment]
> I tried different themes the problems exists but not with arc theme i have installed in local theme installation. It is old but it is the one which does not shows this behaviour.

Aha, do you have same experience with ark themes from fedora reopos?
You need to remove your local theme from ~./themes for testing this.

**Comment by pyaazkaparatha** [comment]
I did. It doesn't occurs. It is to note that i did tried changing themes before posting the bug it occurred with adwaita blackmate traditional blue etc.

**Comment by raveit65** [comment]
Normally, it is is easy for me to find out a setting in theme which fixes the issue, but without having the bug here it is impossible.
What i see in arc themes is that they use 
scrolledwindow overshoot/undershoot {}
instead of
overshoot/undershoot {}
Can you try this with a affected theme?
Another method is to delete complete blocks in gtk-widget.css to find out what causes the issue.
Well, not a nice debugging, but sometimes no other method helps.

**Comment by pyaazkaparatha** [comment]
>Can you try this with a affected theme?

Yes but how?

Also Caja has started crashing now

>Apr 03 12:31:38 localhost.localdomain kernel: caja[9427]: segfault at 8 ip 00007f3a845b3671 sp 00007ffda2ca9790 error 4 in libpython2.7.so.1.0[7f3a844b9000+17a000]
Apr 03 12:31:38 localhost.localdomain systemd-coredump[9440]: Removed old coredump core.caja.1000.a01330e598af4b4397a2d85432158353.19972.1491157336000000.lz4.
Apr 03 12:31:43 localhost.localdomain kernel: caja[9441]: segfault at 8 ip 00007f0578bf2671 sp 00007ffe582d6450 error 4 in libpython2.7.so.1.0[7f0578af8000+17a000]
Apr 03 12:31:43 localhost.localdomain audit[9441]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=9441 comm="caja" exe="/usr/bin/caja" sig=11 res=1
Apr 03 12:31:43 localhost.localdomain systemd-coredump[9454]: Removed old coredump core.caja.1000.a01330e598af4b4397a2d85432158353.19987.1491157342000000.lz4.
Apr 03 12:31:48 localhost.localdomain audit[9455]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=9455 comm="caja" exe="/usr/bin/caja" sig=11 res=1
Apr 03 12:31:48 localhost.localdomain kernel: caja[9455]: segfault at 8 ip 00007f76bc15a671 sp 00007ffff2e23770 error 4 in libpython2.7.so.1.0[7f76bc060000+17a000]
Apr 03 12:31:48 localhost.localdomain systemd-coredump[9469]: Removed old coredump core.caja.1000.a01330e598af4b4397a2d85432158353.20003.1491157347000000.lz4.
Apr 03 12:31:54 localhost.localdomain audit[9470]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=9470 comm="caja" exe="/usr/bin/caja" sig=11 res=1
Apr 03 12:31:54 localhost.localdomain kernel: caja[9470]: segfault at 8 ip 00007fcf2181b671 sp 00007ffd11109c40 error 4 in libpython2.7.so.1.0[7fcf21721000+17a000]
Apr 03 12:31:54 localhost.localdomain systemd-coredump[9484]: Removed old coredump core.caja.1000.a01330e598af4b4397a2d85432158353.20018.1491157352000000.lz4.
Apr 03 12:31:59 localhost.localdomain kernel: caja[9485]: segfault at 8 ip 00007f0eb43d4671 sp 00007ffe627da4b0 error 4 in libpython2.7.so.1.0[7f0eb42da000+17a000]
Apr 03 12:31:59 localhost.localdomain audit[9485]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=9485 comm="caja" exe="/usr/bin/caja" sig=11 res=1
Apr 03 12:31:59 localhost.localdomain systemd-coredump[9501]: Removed old coredump core.caja.1000.a01330e598af4b4397a2d85432158353.20033.1491157358000000.lz4.
Apr 03 12:32:04 localhost.localdomain audit[9502]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=9502 comm="caja" exe="/usr/bin/caja" sig=11 res=1
Apr 03 12:32:04 localhost.localdomain kernel: caja[9502]: segfault at 8 ip 00007f750bb19671 sp 00007ffff8a6e3c0 error 4 in libpython2.7.so.1.0[7f750ba1f000+17a000]
Apr 03 12:32:04 localhost.localdomain systemd-coredump[9516]: Removed old coredump core.caja.1000.a01330e598af4b4397a2d85432158353.20049.1491157363000000.lz4.
bash-4.4$

**Comment by raveit65** [comment]
> Yes but how?

edit /usr/share/themes/Menta/gtk-3.0/gtk-widgets.css if you use Menta theme.

Please open a rhbz report  with a stacktrace for crashes.

**Comment by pyaazkaparatha** [comment]
>edit /usr/share/themes/Menta/gtk-3.0/gtk-widgets.css if you use Menta theme.

Did it

```
/************************
 * overshoot/undershoot *
 ************************/

/* displays at end of mouse scrolling */
scrolledwindow overshoot.top {
    background-image: -gtk-gradient(radial,
                                    center top, 0,
                                    center top, 0.5,
                                    to(@overshoot_bg_color),
                                    to(rgba(158, 179, 137, 0))),
                      -gtk-gradient(radial,
                                    center top, 0,
                                    center top, 0.6,
                                    from(rgba(73, 87, 56, 0.17)),
                                    to(rgba(73, 87, 56, 0)));
    background-size: 100% 5%, 100% 100%;
    background-repeat: no-repeat;
    background-position: center top;
    background-color: transparent;
    border: none;
    box-shadow: none;
}

scrolledwindow overshoot.top:backdrop {
    background-image: -gtk-gradient(radial,
                                    center top, 0,
                                    center top, 0.5,
                                    to(@overshoot_backdrop_bg_color),
                                    to(rgba(137, 145, 131, 0)));
    background-size: 100% 5%;
    background-repeat: no-repeat;
    background-position: center top;
    background-color: transparent;
    border: none;
    box-shadow: none;
}

scrolledwindow overshoot.bottom {
    background-image: -gtk-gradient(radial,
                                    center bottom, 0,
                                    center bottom, 0.5,
                                    to(@overshoot_bg_color),
                                    to(rgba(158, 179, 137, 0))),
                      -gtk-gradient(radial,
                                    center bottom, 0,
                                    center bottom, 0.6,
                                    from(rgba(73, 87, 56, 0.17)),
                                    to(rgba(73, 87, 56, 0)));
    background-size: 100% 5%, 100% 100%;
    background-repeat: no-repeat;
    background-position: center bottom;
    background-color: transparent;
    border: none;
    box-shadow: none;
}

scrolledwindow overshoot.bottom:backdrop {
    background-image: -gtk-gradient(radial,
                                    center bottom, 0,
                                    center bottom, 0.5,
                                    to(@overshoot_backdrop_bg_color),
                                    to(rgba(137, 145, 131, 0)));
    background-size: 100% 5%;
    background-repeat: no-repeat;
    background-position: center bottom;
    background-color: transparent;
    border: none;
    box-shadow: none;
}

scrolledwindow overshoot.left {
    background-image: -gtk-gradient(radial,
                                    left center, 0,
                                    left center, 0.5,
                                    to(@overshoot_bg_color),
                                    to(rgba(158, 179, 137, 0))),
                      -gtk-gradient(radial,
                                    left center, 0,
                                    left center, 0.6,
                                    from(rgba(73, 87, 56, 0.07)),
                                    to(rgba(73, 87, 56, 0)));
    background-size: 5% 100%, 100% 100%;
    background-repeat: no-repeat;
    background-position: left center;
    background-color: transparent;
    border: none;
    box-shadow: none;
}

scrolledwindow overshoot.left:backdrop {
    background-image: -gtk-gradient(radial,
                                    left center, 0,
                                    left center, 0.5,
                                    to(@overshoot_backdrop_bg_color),
                                    to(rgba(137, 145, 131, 0)));
    background-size: 5% 100%;
    background-repeat: no-repeat;
    background-position: left center;
    background-color: transparent;
    border: none;
    box-shadow: none;
}

scrolledwindow overshoot.right {
    background-image: -gtk-gradient(radial,
                                    right center, 0,
                                    right center, 0.5,
                                    to(@overshoot_bg_color),
                                    to(rgba(158, 179, 137, 0))),
                      -gtk-gradient(radial,
                                    right center, 0,
                                    right center, 0.6,
                                    from(rgba(73, 87, 56, 0.07)),
                                    to(rgba(73, 87, 56, 0)));
    background-size: 5% 100%, 100% 100%;
    background-repeat: no-repeat;
    background-position: right center;
    background-color: transparent;
    border: none;
    box-shadow: none;
}

scrolledwindow overshoot.right:backdrop {
    background-image: -gtk-gradient(radial,
                                    right center, 0,
                                    right center, 0.5,
                                    to(@overshoot_backdrop_bg_color),
                                    to(rgba(137, 145, 131, 0)));
    background-size: 5% 100%;
    background-repeat: no-repeat;
    background-position: right center;
    background-color: transparent;
    border: none;
    box-shadow: none;
}

/* result is disable undershoot */
scrolledwindow undershoot.top {
    background-color: transparent;
    background-image: linear-gradient(to left,
                                      rgba(255, 255, 255, 0.2) 50%,
                                      rgba(0, 0, 0, 0.2) 50%);
    background-size: 10px 0px;
    background-repeat: repeat-x;
    background-origin: content-box;
    background-position: center top;
}

scrolledwindow undershoot.bottom {
    background-color: transparent;
    background-image: linear-gradient(to left,
                                      rgba(255, 255, 255, 0.2) 50%,
                                      rgba(0, 0, 0, 0.2) 50%);
    background-size: 10px 0px;
    background-repeat: repeat-x;
    background-origin: content-box;
    background-position: center bottom;
}

scrolledwindow undershoot.left {
    background-color: transparent;
    background-image: linear-gradient(to top,
                                      rgba(255, 255, 255, 0.2) 50%,
                                      rgba(0, 0, 0, 0.2) 50%);
    background-size: 0px 10px;
    background-repeat: repeat-y;
    background-origin: content-box;
    background-position: left center;
}

scrolledwindow undershoot.right {
    background-color: transparent;
    background-image: linear-gradient(to top,
                                      rgba(255, 255, 255, 0.2) 50%,
                                      rgba(0, 0, 0, 0.2) 50%);
    background-size: 0px 10px;
    background-repeat: repeat-y;
    background-origin: content-box;
    background-position: right center;
}

/****************
 * Text Entries *
 ****************/
```

Also 

>Please open a rhbz report with a stacktrace for crashes.

The crashes stopped after removing the nextcloud plugin.

**Comment by raveit65** [comment]
And does it helps ? :-)

**Comment by pyaazkaparatha** [comment]
No. The scrolling problem remains. I think the most weird thing is that it occurs in maximised windows. Scrolling even from keyboard is not possible.

**Comment by pyaazkaparatha** [comment]
No. The scrolling problem remains. I think the most weird thing is that it occurs in maximised windows. Scrolling even from keyboard is not possible.

**Comment by raveit65** [comment]
I have no ideas any more....

**Comment by pyaazkaparatha** [comment]
It has something to do with the theme. After updating the system the adwaita is not showing the problem but menta is.

**Comment by raveit65** [comment]
What did you updated?
Try deleting complete parts from gtk.widget.css to find out the which part causes the issue.
If you see a different undo the delete and remove a smaller part.
And so on and so on until you fond a single or several line which causes the issue.
Sorry, as nobody can reproduce it you're the only one who can find the culprit.

**Comment by pyaazkaparatha** [comment]
The space between right border and grid of files is more whenever the problem occurs but less when it does not that is with arc theme or adwaita now. Look at the screenshots above. Compare with this

![screenshot at 2017-04-06 03-07-52](https://cloud.githubusercontent.com/assets/9029649/24728131/39146124-1a48-11e7-933c-5a52b955dce1.png)


> Try deleting complete parts from gtk.widget.css to find out the which part causes the issue.

Will do it and post tomorrow.

**Comment by pyaazkaparatha** [comment]
I tried it. It didn't helped.  I also replaced the gtk-widget.css with arc's gtk-css. This too didn't helped.Removing the gtk-widget.css file did.

I was able to solve the problem completely by removing a vertical mate-panel i had. None of the themes show errors now. I lost my panel though. It was vertical panel with width of 32(i think).

**Comment by raveit65** [comment]
This is really an example of professional debugging and a good help from reporter. :-)
After adding the vertical panel and playing a bit with the size of it i can reproduce it now.
And i can reproduce it now
- w/o a vertical panel
- with every theme .
It depends on the size between items and the right scrollbar.
With resizing the sidebar, - grap the area between sidebar and view -, you can increase/decrease the size of the space between items and the right scrollbar.
Just in the moment if the size is very huge, i can't scroll any more to the bottom.
Do i decrease this space all is fine.
Ok, this is definitely  a issue with caja as i can reproduce it with every theme.

**Comment by pyaazkaparatha** [comment]
Thanks. It got confirmed. I was thinking of doing a reinstall.

**Comment by raveit65** [comment]
I think you can use the vertical panel again, as you can adjust this with the sidebar.

**Comment by lukefromdc** [comment]
This may be related to a bug affecting both Nemo and Caja in which at certain exact geometries the rename labels don't come up in navigation windows. Resizing the window always fixes that

**Comment by raveit65** [comment]
Indeed, just in the position where scrolling to bottom doesn't work it is impossible to rename a file with F2. Pressing F2 scrolls the window a bit in direction top.
Didn't know that nemo is affected too, as nemo doesn't have the 'scroll to bottom' bug.
Are you sure?

**Comment by raveit65** [comment]
Issue isn't reproducible with MATE gtk3 in rhel7 (gtk+-3.14 ) but with MATE gtk3 in f24 (gtk+-3.20).
I found out that enabling overlay-scrolling via gsettings fixes the problem. This was introduced with gtk+-3.16.
```
[rave@mother ~]$ gsettings get org.mate.interface gtk-overlay-scrolling
true
```
Note, overlay-scrolling is disabled by default with an environment variable in MATE session, in result you need to restart session to see an effect.
Also, overlay-scrolling can make problems with hiding items with the horizontal scrollbar.

Starting caja as root or with sudo shows the same as the env doesn't work here.
Of course the rename problem is also gone.

**Comment by lukefromdc** [comment]
Enabling overlay scrolling is aggravating to some users. In my case I really don't like disappearing widgets, so if I had this bug I would probably have to put up with it rather than resort to overlay scrolling. I can't reproduce it at all, however. Maybe my theme simply does not trigger it, remember that all themes give different widths of widgets that take space away from the view. Also a vertical panel changes the width of a maximized window.

Can anyone who has reproduced this post the exact geometry and the theme of a Caja window exibiting this issue? That might make it easier to reproduce. Also, we need to find out if this affects only GTK 3.20 or also affects GTK 3.22

**Comment by raveit65** [comment]
> Also, we need to find out if this affects only GTK 3.20 or also affects GTK 3.22

I can reproduce it with 3.22 and 3.20 but not with 3.14 (rhel7). I can't test other versions any more as i have only actual fedora/rhel VMs.
But overlay-scrolling was introduce with 3.16. That i couldn't reproduce it with 3.14 gave me the idea to enable overlay-scrolling.

> Can anyone who has reproduced this post the exact geometry and the theme of a Caja window exibiting this issue?

It is independent from the general size of a caja window.
1. you need a huge folder, ie. /etc with caja-icon-view.
2. see screenshot in post https://github.com/mate-desktop/caja/issues/755#issuecomment-290695779
It depends on the distance between the GtkGrid of items to the left vertical scrollbar. You can change this distance with the grip between sidebar and view.

Any ways, i will try it again with a actual version of your theme, maybe it helps.

Btw. setting vertical scrollbar-policy from automatic to always with gtk3-inspector fixes the issue too :-)

**Comment by raveit65** [comment]
@lukefromdc 
with ubuntustudio-legacy and f25 (gtk+-3.22) VM, hope dropbox cloud is fine for you to down load a little video
https://www.dropbox.com/s/0l4hnv7o9l9vkkp/caja-issue.ogv.tar.xz?dl=0

**Comment by lukefromdc** [comment]
Tarball is corrupted

**Comment by raveit65** [comment]
@lukefromdc 
hmm, i could download the tarball and it opens fine.
But here the uncompressed file (< 20 MB).
https://www.dropbox.com/s/8ftp9gois751892/caja-issue.ogv?dl=0

**Comment by lukefromdc** [comment]
I can easily scroll to the bottom of /etc in a caja-icon-view. Keep in mindm, this is with the mouse or keyboard, I do not have any other input devices installed. At this point we should assume I am not going to be able to duplicate this myself so little I can do about it

**Comment by raveit65** [comment]
Weird, it is with your theme in video.

**Comment by lukefromdc** [comment]
The download is being stopped at 207MB, maybe some "security" code
at dropbox? I'll try WGET.

**Comment by lukefromdc** [comment]
Different system. I have never seen this and I am assuming I never will 
be able to duplicate it. Must be more than themes

**Comment by lukefromdc** [comment]
How are you scrolling? I grab the slider directly, I see you have the cursor
floating a ways from it. No idea what that is

**Comment by raveit65** [comment]
I grab the slider with the mouse cursor as this is easier for seeing in a video, but it is the same with using scroll-wheel or with a a touchpad.

**Comment by lukefromdc** [comment]
Was able to duplicate your grab and hold down, then move cursor scroll, still perfect scrolling in my setup. OK, this is more than themes, as you have this and I do not when using the same theme

**Comment by lukefromdc** [comment]
Could screen resolution be involved? I have nothing larger than 1920x1080

**Comment by raveit65** [comment]
Did you change the size of the sidebar with the little area between sidebar and view?
As i did in video.
Resolution in video was 1920x1080 in VM.

**Comment by lukefromdc** [comment]
I tried that, no amount of resizing anything has invoked this for me. I am about to shut down for now, heading out the door

**Comment by pyaazkaparatha** [comment]
This behaviour is also seen in mate-control-center.  mate-control-center-1.18.1-1.fc26.x86_64

**Comment by raveit65** [comment]
Indeed, i can reproduce it with m-c-c window too.
1. open m-c-c window
2. reduce width of the window to 2 rows of items
3. move to slider from right vertical scrollbar to the bottom.
4. grap the window edge on the right side and increase slowly the width of the window until the slider jumps up.
5. Try to scroll to bottom or grab the slider with mouse to bottom,......does not work.

**Comment by raveit65** [comment]
With m-c-c we use GtkTable inside some GtkBoxes and a GtkScrolledWindow, and caja is ported to GtkGrid inside the GtkSrolledwindow, So it's not a problem with using GtkGrid or GtkTable.
It's the GtkScrolledwindow itself.
But it happens only with GtkGrid/Table as we use rows for displaying the items/icons, or what ever.
For this reason you don't see it with a sidebar or caja-list-view as we use a GtkTreeview inside a GtkScrolledWindow.

**Comment by lukefromdc** [comment]
On my setup the slider never jumps up in m-cc when doing the above test unless you reduce window width, and never becomes unable to go to the bottom

**Comment by pyaazkaparatha** [comment]
You can reproduce the bug in this manner.
1- open caja and go to a folder with large number of files like /etc. Scroll to top
2- Now try to adjust sidebar width on left so that the distance between the icon grid is maximum on right.
3- try to scroll down. With anything touchpad /mouse/ keyboard.

I have resolution of 1600x900 with mate themes like menta traditional or blackmate i have reproduced the bug successfully.

**Comment by lukefromdc** [comment]
OK, that was the key: the right side distance has to be absolutely maxed out or this bug does not appear. On my systems I've never seen this by accident and apparently the range in which this happens is small here.

**Comment by pyaazkaparatha** [comment]
>the right side distance has to be absolutely maxed out

I am not 100% sure but it looks like that only.

>this by accident and apparently the range in which this happens is small here.

I too think so but i use a vertical panel which makes it very very common.

**Comment by raveit65** [comment]
For some reasons it is possible to scroll down with the selection ruberband, which make the issue more  and more weird ;-)
I am thinking about to enable overlay-scrolling as default for f26 to fix the issue.
....but i am sure that a lot of fedora Mate users don't like that.

**Comment by lukefromdc** [comment]
I'd sooner document this in the help, along with the overlay scrolling
workaround and window resize workaround than use overlay scrolling
as a default. Also  document the icon view rename bug (rename label
does not appear) that can occur at some exact window sizes in Caja.

Is this scroll issue also present on Nemo, and is it present in Nautilus,
did they never have it, or did they have it and fix it?

**Comment by raveit65** [comment]
@pyaazkaparatha @lukefromdc 
Nemo and Nautilus don't have this issue.
I back ported stuff from them, please test dev-view branch.
https://github.com/mate-desktop/caja/commits/dev-view
The first 2 commits seems to fix the issue
- Add size_request to IconContainer to work around uncecessary relayouting
- eel: Queue resizes on the canvas as elements change visibility

The third one from nemo fixes the space between grid and right vertical scrollbar, but makes it harder to reproduce the issue if you don't use the other commits.
Please test the third one later, i wanna be sure that scroll and renaming issue is fixed.
@pyaazkaparatha 
RPM coming soon for testing.

**Comment by lukefromdc** [comment]
I'll test these when I get home. On the road with a tiny Intel Atom netbook
at the moment and will have to leave at an unpredictable time.

**Comment by raveit65** [comment]
@pyaazkaparatha 
scratch builds from koji build sever
1. build for fixing the issue
https://koji.fedoraproject.org/koji/taskinfo?taskID=18953718
2. build with fix for the grid
https://koji.fedoraproject.org/koji/taskinfo?taskID=18953847
Please test.

**Comment by pyaazkaparatha** [comment]
I installed all the three packages caja extensions and schemas and tested them serially.

The issue is still present but its presentation is different. The amount of area not scrolled has decreased and grid has become weird.

![screenshot at 2017-04-13 00-32-57](https://cloud.githubusercontent.com/assets/9029649/24975239/8c57b69e-1fb4-11e7-87af-035e7a3dabb2.png)

**Comment by raveit65** [comment]
Please try first caja-1.18.1-2.fc26, i am not sure about the grid fix, as comment in nemo PR sounds not good after merging.
https://github.com/linuxmint/nemo/pull/1257

**Comment by pyaazkaparatha** [comment]
I did. First .2 then .3 one by one. Serially.

**Comment by raveit65** [comment]
Maybe it's to late, /etc looks like this here with caja-1.18.1-3.fc26 and i can 't reproduce the issue anymore.
![bildschirmfoto zu 2017-04-12 21-36-20](https://cloud.githubusercontent.com/assets/961604/24976108/74c88684-1fc8-11e7-9b60-811f93ffacd2.png)

Did you restart caja?
'killall caja'

**Comment by pyaazkaparatha** [comment]
i changed the sidebar width to produce the bug. The bug occurs at some point but i am not able to describe what point. Try changing sidbar width slight at a time and test.

`bash-4.4$ rpmquery caja
caja-1.18.1-3.fc26.x86_64`

**Comment by lukefromdc** [comment]
I can't reproduce it with these commits but in order to do so at all had to know the exact condition in the first place, as this was touchy to invoke here. In all other ways this seems to work fine, and Caja didn't get the screwy rename bug on one column/long filename reported by a Nemo user. I tested that with a directory full of copied very long filename (3 full rows) files, and had no issue, probably we are using a shorter row/more rows layout than Nemo for that. The dynamic resizing of the grid works, Nemo also does this, Nautilus does not at this point.

**Comment by pyaazkaparatha** [comment]
>Did you restart caja?
'killall caja'

I closed it but not killall. I am not able to reproduce the bug after killall.

**Comment by lukefromdc** [comment]
What looks unfamiliar about the grid is that the spacing between icons changes with the width of thew view, which is also the case in Nemo. Yes, it looks different

**Comment by raveit65** [comment]
> I closed it but not killall. I am not able to reproduce the bug after killall.

\o/\o/\o/\o/\o/\o/
Caja handles the desktop, in result you need to kill the whole process.

Well, i am not sure about grid commit as it looks different and this comment sounds not good.
https://github.com/linuxmint/nemo/pull/1257#issuecomment-246989121

**Comment by lukefromdc** [comment]
That comment was about long filenames getting pushed off to the right, which I was unable to duplicate in a test with Caja probably due to some difference in the format of the label when renaming

**Comment by lukefromdc** [comment]
Got a build going with just the first two commits, let's see if we can leave the grid alone

**Comment by lukefromdc** [comment]
OK, in an A-B-A test between just the first two commits (without the grid change) and Caja master, and reopening with the geometry invoking the bug saved, this works. Master caja /etc with widest right wide gap, can't scroll to bottom,apply first two commits, build, install, restart Caja, caja /etc, can scroll to bottom, reinstall master and restart caja /etc and again can't scroll to bottom. We don't need the grid change and Caja looks better without it.

**Comment by pyaazkaparatha** [comment]
The bug is closed but the fix doesn't works properly. The file grids are all not really looking like grid
![screenshot at 2017-10-26 01-54-05](https://user-images.githubusercontent.com/9029649/32021305-a24d5310-b9f0-11e7-9759-5233fc2d6b61.png)

**Comment by lukefromdc** [comment]
What exactly do you mean? Can you post a screenshot? Use a folder full of dummy files if necessary. I can't duplicate the original bug after the fix for this and certainly have not seen it

**Comment by pyaazkaparatha** [comment]
i have attached a screenshot above.

**Comment by lukefromdc** [comment]
I have never seen that sort of problem. Looks like in your case the length of the label determines the width of the space given to an icon. What version of Caja are you using, and with what GTK version?

At any rate, you should open a new issue for this if it does not turn out to be something like what I am about to decribe below:

Make sure that view ->Arrange Items is not set to "manual" as then files can be placed anywhere and I suppose this sort of thing could happen.

**Comment by pyaazkaparatha** [comment]
The arrange icons shows by modification date. The reason i posted this here because it happened after this fix.

**Comment by pyaazkaparatha** [comment]
caja-1.19.2-1.fc27.x86_64

Fedora 27

The screenshot has /etc folder.

**Comment by lukefromdc** [comment]
I think I found your problem: Do you have "compact layout" (NOT "compact view") selected? I found that if I set compact layout I got the same thing.  Try turning that off and see what you get. I have no idea if that is the intended behavior or not in compact layout. If it is not, we have a new issue affecting not the compactr view but the compact layout option available in "view" when and only when icon view is selected

**Comment by pyaazkaparatha** [comment]
Correct.

**Comment by lukefromdc** [comment]
Icon view is the default, but in Caja compact layout within it is not. Didn't come up that way in a blank new user directory, and this code from the schema confirms it:

```
    <key name="default-use-tighter-layout" type="b">
      <default>false</default>
      <summary>Use tighter layout in new windows</summary>
      <description>If true, icons will be laid out tighter by default in new windows.</description>
    </key>

```

I would not be surprised though if at some point Nautilus (from which Caja is forked) had that as a default

**Comment by raveit65** [comment]
I can reproduce it with 
[rave@f27 ~]$ rpm -qa caja
caja-1.19.2-1.fc27.x86_64
Sadly, i can't revert this layout any more here for this folder.
We should really drop this option.
But, can you please file out another report for it?
Scrolling isn't affected by this layout problem.

**Comment by lukefromdc** [comment]
@raveit65, yiou means to say you have a folder stuck on a particular option and can't change it? If so, try setting it to list-view or compact view and then setting it back. If nothing works, that would imply you have a corrupted file or one with a permissions issue somewhere. Worst case, make a new directory, move the contents of the problem one to it, then delete the old one but save its name on a text file. Log out and back in, rename the new directory back to the old name, see if that does it. If nothing works you might have to reset your dconf database and/or trash files related to caja in .config

**Comment by raveit65** [comment]
@lukefromdc 
> you means to say you have a folder stuck on a particular option and can't change it?

Yes, i used /etc folder and setting default-use-tighter-layout to false doesn't have any effect.
But it's only a VM for testing.
Deleting both user dconf files and restarting session doesn't help.
~.config/dconf/user
/run/user/1000/dconf/user.
This is more than weird.
Maybe i need to delete gvfs files?

**Comment by raveit65** [comment]
Hmm, same problem with nemo -_-
After set 'compact layout' to true in nemo preferences one time, uncheck the setting doesn't have any effect for /etc folder.

**Comment by lukefromdc** [comment]
On Debian Unstable with current gtk3.22 (from the git branch as of 10-27-2017 as I am looking at another issue), I was able to freely check and uncheck compact layout with no problems. Could do so in same window, after closing and reopening that window, or restarting caja. The preference held and behavior followed it each time.

There is a bug in Caja and Nemo where it is possible for the preferences to be unwriteable in some way, usually you see this when running as root and finding you can switch out of the default view but it always comes back in the next window set to that location.

**Comment by raveit65** [comment]
Ok, i found the problem, btw. a quick and dirty fix.
Deleting the content of 
```
[rave@f27 ~]$ ls -l .local/share/gvfs-metadata/
insgesamt 72
-rw-------. 1 rave rave   320 29. Okt 20:55 home
-rw-r--r--. 1 rave rave 32768 29. Okt 20:55 home-5fe8717f.log
-rw-------. 1 rave rave    92 29. Okt 20:55 root
-rw-r--r--. 1 rave rave 32768 29. Okt 20:55 root-c15cd5f3.log
```
and a quick session restart, before those files were created again, fixes the problem here.
I did that several times, --enabling the option for a folder and deleting those files--, and it is 100% reproducible. This was with non-released f27. (beta)
Now i will check if this is a issue with f26/f25 and 1.18.x too.

**Comment by raveit65** [comment]
I can reproduce the issue with f26 and caja-1.18.4 too.
The only different here is that toogle the  'compact layout' option works first, but let say toggling the option 20 times or so the issue bumped in.
I don't have a f26 VM with Mate-1.19x, so i cant test more.
Sorry, i don't want to test this on my production system with f26 and latest 1.19 releases.
Honestly this is a serious issue and i like to see a way to disable this option for f27 with a patch, until we know exactly what#s the problem is.
@pyaazkaparatha 
I hope you can fix your f27 installation with this workaround.

**Comment by pyaazkaparatha** [comment]
The lukefromdc's advice worked for me. I changed the view.  The option was already disabled in dconf. Thanks for the help.

**Comment by lukefromdc** [comment]
Any option showing disabled in dconf-editor but enabled in the preferences GUI either is a bug or indicates a bug elsewhere

**Comment by raveit65** [comment]
> Any option showing disabled in dconf-editor but enabled in the preferences GUI either is a bug or indicates a bug elsewhere

Not exactly my problem here.
After i enabled and disabled the option one time in preferences, and the checkbox is unchecked + option is false in dconf, the icon view is wrong like the pic at https://github.com/mate-desktop/caja/issues/755#issuecomment-293679651
, until i delete the content of 
```
[rave@f27 ~]$ ls -l .local/share/gvfs-metadata/
insgesamt 72
-rw-------. 1 rave rave   320 29. Okt 20:55 home
-rw-r--r--. 1 rave rave 32768 29. Okt 20:55 home-5fe8717f.log
-rw-------. 1 rave rave    92 29. Okt 20:55 root
-rw-r--r--. 1 rave rave 32768 29. Okt 20:55 root-c15cd5f3.log
```
Hope this post makes it clear.
I tested it also with other folders than /etc.
As it is much worse in f27 i asked for a patch to disable the whole function.
